### ISSUE TITLE
if, else-if, else structure

### ISSUE THREAD

**Issue by maelso** [inducer/cgen#18]
Hello, guys, 

Is it possible to generate if-else-if structure using cgen?

if (condition_1) declaration_1;
else if (condition_2) declaration_2;
else if (condition_3) declaration_3;
. 
. 
. 
else if (condition_n) declaration_n;
else declaration_default;

**Comment by maelso** [comment]
I'm using make_multiple_ifs. It returns me a structure like this:

if (condition_1) declaration_1;
else:
    if (condition_2) declaration_2;
    else:
        if (condition_3) declaration_3;
        ...
I think this is the right way to use cgen, right?

**Comment by inducer** [comment]
Yes, that should work.
