### ISSUE TITLE
Please push cgen==2018.1 to PyPi

### ISSUE THREAD

**Issue by lokraszewski** [inducer/cgen#22]
Hi @inducer, thanks for maintaining the project it's very useful. 
Looking at https://pypi.org/project/cgen/#history I don't see the latest release. 

I would like to make use of the recently addded `ifndef` support.

```
import cgen as c

test = c.IfNDef("SOME_DEF",[c.Comment("Test1")],[c.Comment("Test2")])

print(test)
```

**Comment by inducer** [comment]
Thanks for the nudge. I would like to wait until #23 is in, since that has sat around unfixed for way too long.

**Comment by inducer** [comment]
Done. 2019.1 is now on the package index.

**Comment by lokraszewski** [comment]
@inducer great thanks!
