### ISSUE TITLE
Classes for IfDef and InlineInitializers

### ISSUE THREAD

**Issue by navjotk** [inducer/cgen#7]
While trying to modify [opesci-fd](https://github.com/opesci/opesci-fd) to use this project's code generation capabilities, there were some classes I would have found helpful but couldn't find them in cgen. I added them to a [wrapper](https://github.com/opesci/opesci-fd/pull/60/files#diff-b983b01b8b0f28b427c67ecb562fc390) and used them in the project. These include a class for IfDef and one for InlineInitializers. If you think they would be helpful to this project, I could submit a pull request here.

**Comment by inducer** [comment]
Sure, I'd love to have a PR.
